### ISSUE TITLE
Windows tmpfile permissions error

### ISSUE THREAD

**Issue by livherdman** [noaa-ocs-modeling/OCSMesh#118] opened 2023-10-31 19:13 UTC
Issues with permissions and tempfiles on windows machine. 
I was able to fix it with a few small additions to the code. I am not sure how to share the changes with you...
I have attached the output from git diff as a file for folks that run into the same issue. It is apparently related to the difference between how linux and windows os interact with tempfile.
[windows_changes.txt](https://github.com/noaa-ocs-modeling/OCSMesh/files/13220548/windows_changes.txt)

**Comment by SorooshMani-NOAA** [comment] 2023-11-09 12:57
Copying the diff here for easier review:
```diff
diff --git a/ocsmesh/geom/collector.py b/ocsmesh/geom/collector.py
index 4d6a69b..3dfd705 100644
--- a/ocsmesh/geom/collector.py
+++ b/ocsmesh/geom/collector.py
@@ -289,7 +289,7 @@ class GeomCollector(BaseGeom):
 
         epsg4326 = CRS.from_user_input("EPSG:4326")
         mp = None
-        with tempfile.TemporaryDirectory() as temp_dir:
+        with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as temp_dir:
             feather_files = []
 
             temp_path = Path(temp_dir)
diff --git a/ocsmesh/hfun/collector.py b/ocsmesh/hfun/collector.py
index c17f5dd..851e7ee 100644
--- a/ocsmesh/hfun/collector.py
+++ b/ocsmesh/hfun/collector.py
@@ -828,7 +828,7 @@ class HfunCollector(BaseHfun):
 
         elif self._method == 'fast':
 
-            with tempfile.TemporaryDirectory() as temp_dir:
+            with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as temp_dir:
                 rast = self._create_big_raster(temp_dir)
                 hfun = self._apply_features_fast(rast)
                 composite_hfun = self._get_hfun_composite_fast(hfun)
diff --git a/ocsmesh/ops/combine_geom.py b/ocsmesh/ops/combine_geom.py
index 30412c1..ef8a07a 100644
--- a/ocsmesh/ops/combine_geom.py
+++ b/ocsmesh/ops/combine_geom.py
@@ -165,7 +165,7 @@ class GeomCombine:
         _logger.info(f"Number of processes: {nprocs}")
         with tempfile.TemporaryDirectory(dir=out_dir) as temp_dir, \
                 tempfile.NamedTemporaryFile() as base_file:
-
+            base_file.close()
             if base_mult_poly:
                 base_mesh_path = base_file.name
                 self._multipolygon_to_disk(
diff --git a/ocsmesh/raster.py b/ocsmesh/raster.py
index 16d6a43..f59d379 100644
--- a/ocsmesh/raster.py
+++ b/ocsmesh/raster.py
@@ -383,6 +383,7 @@ class Raster:
         try:
             # pylint: disable=R1732
             tmpfile = tempfile.NamedTemporaryFile(prefix=tmpdir)
+            tmpfile.close()
 
             new_meta = kwargs
             # Flag to workaround cases where "src" is NOT set yet
diff --git a/submodules/jigsaw-python b/submodules/jigsaw-python
index 77ee95f..d9d70e6 160000
--- a/submodules/jigsaw-python
+++ b/submodules/jigsaw-python
@@ -1 +1 @@
-Subproject commit 77ee95f9dbd05dc981e113e67e6edcb113d8862b
+Subproject commit d9d70e60fae9b5686c85113d1d1d4b21ae341789

```

**Comment by SorooshMani-NOAA** [comment] 2023-11-09 20:58
Thank you @livherdman. I need more time to test this. I'll get back to you about your proposed changes.

**Comment by SorooshMani-NOAA** [comment] 2023-11-13 16:55
@livherdman I'm testing your changes on a windows based environment. It helps with some of the test (this is the first time I'm running the test on windows), but many more still fail due to permissions issues. I think some significant adjustments need to be made in temporary file handling before the issue is fully resolved. 

I keep your changes as reference, but for now I don't have plan for merging them to `main` branch. Thank you again for opening this issue and your suggested changes.

**Comment by SorooshMani-NOAA** [comment] 2023-11-18 04:28
@livherdman this ticket motivated me to look into running the tests for Windows as well as a part of automated testing. I update the OCSMesh code and how it uses the temp-files so that it works on Windows too.

After I merge the bugfix branch to `main`, please test the latest and let me know if it resolves your issue or not.

Thanks a lot!

**Comment by SorooshMani-NOAA** [comment] 2023-11-18 04:30
@livherdman the merge automatically close the ticket, but please feel free to reopen it if the issue is not resolved in the latest main. If that's the case, then kindly please provide a test case that fails as well for me to investigate.

Thank you.

**Closed as completed** 2023-11-18 04:29 UTC
